config:

  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - abbr
      - acronym
      - div
      - kbd
      - sup
  no-duplicate-heading: false

globs:

- "**/*.md"
- "*.md"

ignores:

- "site/**/*.md"
- ".github/**/*.md"
- "renv/**/*.md"
- "index.md"
- "README.md"

fix: true
