[workspace]
name = "documentation"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
git = "*"
pre-commit = "*"
r-sandpaper = "*"
r-varnish = "*"

[tasks]
serve = "Rscript -e 'sandpaper::serve()'"
build = "Rscript -e 'sandpaper::build_lesson()'"
check = "Rscript -e 'sandpaper::check_lesson()'"
lint = "pre-commit run --all-files"
